# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeCliTools < Formula
  desc "CLI tools for Claude Code protocol"
  homepage "https://github.com/mzhaom/claude-cli-protocol"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mzhaom/claude-cli-protocol/releases/download/v0.1.0/claude-cli-tools-0.1.0-darwin-amd64.tar.gz"
      sha256 "170028ea5d2e2a5a0c9501cdf6d72d9055e4bec7c146521907d4a2c0684d801a"

      def install
        bin.install "yoloplanner"
        bin.install "yoloswe"
        bin.install "sessionplayer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mzhaom/claude-cli-protocol/releases/download/v0.1.0/claude-cli-tools-0.1.0-darwin-arm64.tar.gz"
      sha256 "14db6d3b9db33d90a6e056747c68332817c0526c03ea059c37d3ffb232c3e564"

      def install
        bin.install "yoloplanner"
        bin.install "yoloswe"
        bin.install "sessionplayer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mzhaom/claude-cli-protocol/releases/download/v0.1.0/claude-cli-tools-0.1.0-linux-amd64.tar.gz"
      sha256 "ff719520b452dd646353035fe3bdd6e1106a23cfd8209a729e9871f237fa44af"
      def install
        bin.install "yoloplanner"
        bin.install "yoloswe"
        bin.install "sessionplayer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mzhaom/claude-cli-protocol/releases/download/v0.1.0/claude-cli-tools-0.1.0-linux-arm64.tar.gz"
      sha256 "4fb72f6f069bddf4428201fa3b243ae726ec5192ce7afb365706ce905f5459a0"
      def install
        bin.install "yoloplanner"
        bin.install "yoloswe"
        bin.install "sessionplayer"
      end
    end
  end
end
